//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton;

@interface BLAboutViewController : UIViewController
{
    UIButton *_reviewButton;
}

@property(retain, nonatomic) UIButton *reviewButton; // @synthesize reviewButton=_reviewButton;
- (void).cxx_destruct;
- (void)doneAction:(id)arg1;
- (void)reviewAction:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)awakeFromNib;

@end

