//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSError, NSHTTPURLResponse, NSSet, NSURL;

@interface BLCacheOperation : NSOperation
{
    _Bool _internalUseOnly;
    NSURL *_sourceURL;
    NSURL *_destinationURL;
    unsigned long long _downloadPriority;
    NSURL *_redirectURL;
    NSSet *_cssURLs;
    NSSet *_otherURLs;
    NSError *_error;
    unsigned long long _size;
    NSHTTPURLResponse *_response;
}

+ (id)cacheOperationWithFileURL:(id)arg1;
+ (id)cacheOperationWithHTTPAddress:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property _Bool internalUseOnly; // @synthesize internalUseOnly=_internalUseOnly;
@property(retain) NSHTTPURLResponse *response; // @synthesize response=_response;
@property unsigned long long size; // @synthesize size=_size;
@property(retain) NSError *error; // @synthesize error=_error;
@property(retain) NSSet *otherURLs; // @synthesize otherURLs=_otherURLs;
@property(retain) NSSet *cssURLs; // @synthesize cssURLs=_cssURLs;
@property(retain) NSURL *redirectURL; // @synthesize redirectURL=_redirectURL;
@property unsigned long long downloadPriority; // @synthesize downloadPriority=_downloadPriority;
@property(retain, nonatomic) NSURL *destinationURL; // @synthesize destinationURL=_destinationURL;
@property(retain, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
- (void).cxx_destruct;
- (_Bool)isReady;
- (void)main;
- (id)init;
- (id)initWithSourceURL:(id)arg1 destinationURL:(id)arg2;

@end

