//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperationQueue.h"

#import "NSURLSessionDataDelegate.h"
#import "NSURLSessionDownloadDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, NSURLSession, Reachability;

@interface BLCache : NSOperationQueue <NSURLSessionDataDelegate, NSURLSessionDownloadDelegate>
{
    _Bool _allowsCellularAccess;
    _Bool _applicationActive;
    _Bool _suspendBackgroundTasks;
    _Bool _backgroundSessionActivity;
    Reachability *_reachability;
    id <BLCacheDelegate> _delegate;
    NSURLSession *_ephemeralSession;
    NSURLSession *_backgroundSession;
    NSMutableDictionary *_pendingCacheOperationsByURL;
    NSMutableDictionary *_pendingSessionTasksByURL;
    NSMutableDictionary *_sessionOutcomesByURL;
    NSMutableArray *_finishedCacheOperations;
    long long _networkStatus;
    CDUnknownBlockType _backgroundSessionCompletionHandler;
    unsigned long long _backgroundTaskIdentifier;
}

+ (id)normalisedURLWithString:(id)arg1 cacheURL:(id *)arg2;
+ (id)cacheURL;
+ (void)registerNetworkActivityHandler:(CDUnknownBlockType)arg1;
+ (void)endNetworkActivity:(id)arg1;
+ (void)beginNetworkActivity:(id)arg1;
+ (_Bool)isNetworkActivity;
+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
@property(copy, nonatomic) CDUnknownBlockType backgroundSessionCompletionHandler; // @synthesize backgroundSessionCompletionHandler=_backgroundSessionCompletionHandler;
@property(nonatomic) _Bool backgroundSessionActivity; // @synthesize backgroundSessionActivity=_backgroundSessionActivity;
@property(nonatomic) _Bool suspendBackgroundTasks; // @synthesize suspendBackgroundTasks=_suspendBackgroundTasks;
@property(nonatomic) _Bool applicationActive; // @synthesize applicationActive=_applicationActive;
@property(nonatomic) long long networkStatus; // @synthesize networkStatus=_networkStatus;
@property(retain, nonatomic) NSMutableArray *finishedCacheOperations; // @synthesize finishedCacheOperations=_finishedCacheOperations;
@property(retain, nonatomic) NSMutableDictionary *sessionOutcomesByURL; // @synthesize sessionOutcomesByURL=_sessionOutcomesByURL;
@property(retain, nonatomic) NSMutableDictionary *pendingSessionTasksByURL; // @synthesize pendingSessionTasksByURL=_pendingSessionTasksByURL;
@property(retain, nonatomic) NSMutableDictionary *pendingCacheOperationsByURL; // @synthesize pendingCacheOperationsByURL=_pendingCacheOperationsByURL;
@property(retain, nonatomic) NSURLSession *backgroundSession; // @synthesize backgroundSession=_backgroundSession;
@property(retain, nonatomic) NSURLSession *ephemeralSession; // @synthesize ephemeralSession=_ephemeralSession;
@property __weak id <BLCacheDelegate> delegate; // @synthesize delegate=_delegate;
@property _Bool allowsCellularAccess; // @synthesize allowsCellularAccess=_allowsCellularAccess;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
- (void).cxx_destruct;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(id)arg1;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didResumeAtOffset:(long long)arg3 expectedTotalBytes:(long long)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 willCacheResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 willPerformHTTPRedirection:(id)arg3 newRequest:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)processPendingCacheOperations;
- (void)flushFinishedCacheOperations:(CDUnknownBlockType)arg1;
- (void)registerBackgroundSessionCompletionHandler:(CDUnknownBlockType)arg1;
- (void)collectGarbage:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteURLs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)suspendDownloads;
- (void)resumeDownloads;
- (void)setMaxConcurrentOperationCount:(long long)arg1;
- (void)addOperations:(id)arg1 waitUntilFinished:(_Bool)arg2;
- (void)addOperation:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

