//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError, NSURLRequest, NSURLResponse;

@interface BLCacheURLProtocolClientCallback : NSObject
{
    _Bool _finished;
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSData *_data;
    NSError *_error;
    unsigned long long _policy;
}

@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) unsigned long long policy; // @synthesize policy=_policy;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;

@end

