//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

@class NSArray, NSFileHandle, NSHTTPURLResponse, NSNumber, NSThread, NSURL, NSURLSessionDataTask;

@interface BLCacheURLProtocol : NSURLProtocol
{
    _Bool _refreshCache;
    NSThread *_thread;
    NSArray *_modes;
    NSURL *_cacheURL;
    NSNumber *_fileSize;
    NSFileHandle *_fileHandle;
    NSHTTPURLResponse *_response;
    NSURLSessionDataTask *_dataTask;
}

+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
+ (_Bool)canInitWithURLString:(id)arg1;
@property __weak NSURLSessionDataTask *dataTask; // @synthesize dataTask=_dataTask;
@property(retain) NSHTTPURLResponse *response; // @synthesize response=_response;
@property(retain) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
@property(retain) NSNumber *fileSize; // @synthesize fileSize=_fileSize;
@property _Bool refreshCache; // @synthesize refreshCache=_refreshCache;
@property(retain) NSURL *cacheURL; // @synthesize cacheURL=_cacheURL;
@property(retain) NSArray *modes; // @synthesize modes=_modes;
@property(retain) NSThread *thread; // @synthesize thread=_thread;
- (void).cxx_destruct;
- (void)performClientCallback:(id)arg1;
- (_Bool)readCacheFile;
- (void)stopLoading;
- (void)startLoading;
- (id)initWithRequest:(id)arg1 cachedResponse:(id)arg2 client:(id)arg3;

@end

