//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UISearchResultsUpdating.h"

@class BLFeedly, NSArray, NSMutableDictionary, NSString, NSURLSession, UISearchController, UITableView;

@interface BLFeedSearchViewController : UITableViewController <UISearchResultsUpdating>
{
    NSArray *_topics;
    UISearchController *_searchController;
    UITableView *_searchTableView;
    NSURLSession *_imageSession;
    BLFeedly *_feedly;
    NSArray *_feeds;
    NSMutableDictionary *_feedsByQuery;
    NSMutableDictionary *_imageByVisualURL;
}

@property(retain, nonatomic) NSMutableDictionary *imageByVisualURL; // @synthesize imageByVisualURL=_imageByVisualURL;
@property(retain, nonatomic) NSMutableDictionary *feedsByQuery; // @synthesize feedsByQuery=_feedsByQuery;
@property(retain, nonatomic) NSArray *feeds; // @synthesize feeds=_feeds;
@property(retain, nonatomic) BLFeedly *feedly; // @synthesize feedly=_feedly;
@property(retain, nonatomic) NSURLSession *imageSession; // @synthesize imageSession=_imageSession;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) NSArray *topics; // @synthesize topics=_topics;
- (void).cxx_destruct;
- (void)doneAction:(id)arg1;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

