//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class BLFeedly, NSMutableArray, NSMutableSet, NSString;

@interface BLFeedViewController : UITableViewController
{
    _Bool _subscription;
    BLFeedly *_feedly;
    NSString *_identifier;
    NSMutableSet *_selectedFolderIdentifiers;
    NSMutableArray *_folderIdentifiers;
    NSMutableArray *_folderTitles;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(retain, nonatomic) NSMutableArray *folderTitles; // @synthesize folderTitles=_folderTitles;
@property(retain, nonatomic) NSMutableArray *folderIdentifiers; // @synthesize folderIdentifiers=_folderIdentifiers;
@property(retain, nonatomic) NSMutableSet *selectedFolderIdentifiers; // @synthesize selectedFolderIdentifiers=_selectedFolderIdentifiers;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) _Bool subscription; // @synthesize subscription=_subscription;
@property(retain, nonatomic) BLFeedly *feedly; // @synthesize feedly=_feedly;
- (void).cxx_destruct;
- (void)setFeedlyFeed:(id)arg1;
- (void)setNewsFeed:(id)arg1;
- (void)refresh;
- (void)doneAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

