//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface BLFeedlyItem : NSObject
{
    _Bool _unread;
    _Bool _saved;
    NSString *_identifier;
    NSDate *_crawledDate;
    NSString *_link;
    NSString *_title;
    NSString *_author;
    NSString *_content;
    NSString *_summary;
    NSString *_sourceTitle;
    NSString *_sourceStreamID;
}

+ (id)itemWithJSONDictionary:(id)arg1;
+ (void)initialize;
@property(nonatomic) _Bool saved; // @synthesize saved=_saved;
@property(nonatomic) _Bool unread; // @synthesize unread=_unread;
@property(retain, nonatomic) NSString *sourceStreamID; // @synthesize sourceStreamID=_sourceStreamID;
@property(retain, nonatomic) NSString *sourceTitle; // @synthesize sourceTitle=_sourceTitle;
@property(retain, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) NSDate *crawledDate; // @synthesize crawledDate=_crawledDate;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)condensedPlaintextFromHTML:(id)arg1 maxCharacters:(unsigned long long)arg2;

@end

