//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CAShapeLayer, NSDate, NSNumber, NSSet, NSString, UILabel;

@interface BLItemTableViewCell : UITableViewCell
{
    _Bool _unread;
    _Bool _saved;
    _Bool _cached;
    NSDate *_date;
    NSString *_feed;
    NSString *_title;
    NSString *_summary;
    NSSet *_searchTerms;
    CDUnknownBlockType _editHandler;
    double _fontSize;
    UILabel *_dateLabel;
    UILabel *_feedLabel;
    UILabel *_titleLabel;
    UILabel *_summaryLabel;
    CAShapeLayer *_unreadShapeLayer;
    CAShapeLayer *_savedShapeLayer;
    NSNumber *_editUnread;
    NSNumber *_editSaved;
}

+ (id)greyColour;
+ (double)heightForPreferredContentSizeCategory:(id)arg1;
+ (id)unsearchableCharacterSet;
@property(retain, nonatomic) NSNumber *editSaved; // @synthesize editSaved=_editSaved;
@property(retain, nonatomic) NSNumber *editUnread; // @synthesize editUnread=_editUnread;
@property(retain, nonatomic) CAShapeLayer *savedShapeLayer; // @synthesize savedShapeLayer=_savedShapeLayer;
@property(retain, nonatomic) CAShapeLayer *unreadShapeLayer; // @synthesize unreadShapeLayer=_unreadShapeLayer;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *feedLabel; // @synthesize feedLabel=_feedLabel;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(copy, nonatomic) CDUnknownBlockType editHandler; // @synthesize editHandler=_editHandler;
@property(nonatomic) _Bool cached; // @synthesize cached=_cached;
@property(nonatomic) _Bool saved; // @synthesize saved=_saved;
@property(nonatomic) _Bool unread; // @synthesize unread=_unread;
@property(retain, nonatomic) NSSet *searchTerms; // @synthesize searchTerms=_searchTerms;
@property(retain, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *feed; // @synthesize feed=_feed;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (void).cxx_destruct;
- (void)setPreferredContentSizeCategory:(id)arg1;
- (void)setCached:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSaved:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setUnread:(_Bool)arg1 animated:(_Bool)arg2;
- (void)refreshShapeLayers:(_Bool)arg1;
- (id)attributedStringWithString:(id)arg1 fontSize:(double)arg2 sizeToFit:(struct CGSize)arg3;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)tintColorDidChange;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

