//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString;

@interface BLListTableViewCell : UITableViewCell
{
    int _unread;
    NSString *_title;
    long long _icon;
}

+ (double)heightForPreferredContentSizeCategory:(id)arg1;
@property(nonatomic) long long icon; // @synthesize icon=_icon;
@property(nonatomic) int unread; // @synthesize unread=_unread;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)setPreferredContentSizeCategory:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

