//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "NSUserActivityDelegate.h"
#import "UIDataSourceModelAssociation.h"
#import "UISearchResultsUpdating.h"
#import "UIViewControllerPreviewingDelegate.h"

@class BLItemViewController, BLNewsList, NSFetchedResultsController, NSSet, NSString, NSUserActivity, UINavigationController, UISearchController, UITableView;

@interface BLListViewController : UITableViewController <NSFetchedResultsControllerDelegate, UIViewControllerPreviewingDelegate, UIDataSourceModelAssociation, UISearchResultsUpdating, NSUserActivityDelegate>
{
    _Bool _collapsed;
    NSFetchedResultsController *_itemsFetchedResultsController;
    UINavigationController *_itemNavigationController;
    BLNewsList *_newsList;
    UISearchController *_searchController;
    UITableView *_searchTableView;
    NSSet *_searchTerms;
    NSUserActivity *_userActivity;
}

@property(retain, nonatomic) NSUserActivity *userActivity; // @synthesize userActivity=_userActivity;
@property(retain, nonatomic) NSSet *searchTerms; // @synthesize searchTerms=_searchTerms;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) _Bool collapsed; // @synthesize collapsed=_collapsed;
@property(retain, nonatomic) BLNewsList *newsList; // @synthesize newsList=_newsList;
@property(retain, nonatomic) UINavigationController *itemNavigationController; // @synthesize itemNavigationController=_itemNavigationController;
@property(retain, nonatomic) NSFetchedResultsController *itemsFetchedResultsController; // @synthesize itemsFetchedResultsController=_itemsFetchedResultsController;
- (void).cxx_destruct;
@property(readonly, nonatomic) BLItemViewController *itemViewController;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerWillChangeContent:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)indexPathForElementWithModelIdentifier:(id)arg1 inView:(id)arg2;
- (id)modelIdentifierForElementAtIndexPath:(id)arg1 inView:(id)arg2;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)updateSearchResultsForSearchController:(id)arg1;
- (void)updateBackButton;
- (void)updateUserActivity;
- (void)updateTableViewSelection:(_Bool)arg1;
- (void)configureCell:(id)arg1 withNewsItem:(id)arg2 animated:(_Bool)arg3;
- (void)refresh;
- (void)titleAction:(id)arg1;
- (void)swipeAction:(id)arg1;
- (void)markAllAsReadAction:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)userActivityWillSave:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

