//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

@class UIProgressView;

@interface BLNavigationController : UINavigationController
{
    UIProgressView *_progressView;
}

@property(readonly, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (id)previewActionItems;
- (void)viewDidLayoutSubviews;

@end

