//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSSet, NSString;

@interface BLNewsCacheNode : NSManagedObject
{
}


// Remaining properties
@property(nonatomic) int activity; // @dynamic activity;
@property(retain, nonatomic) NSSet *ancestors; // @dynamic ancestors;
@property(nonatomic) int cachedSize; // @dynamic cachedSize;
@property(retain, nonatomic) NSSet *descendants; // @dynamic descendants;
@property(nonatomic) NSString *identifier; // @dynamic identifier;
@property(nonatomic) _Bool parseable; // @dynamic parseable;
@end

