//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLNewsList.h"

@class NSSet, NSString, NSURL;

@interface BLNewsFeed : BLNewsList
{
}

@property(readonly, nonatomic) NSURL *iconURL;

// Remaining properties
@property(nonatomic) NSSet *folders; // @dynamic folders;
@property(retain, nonatomic) NSString *iconString; // @dynamic iconString;

@end

