//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLNewsList.h"

@class NSSet;

@interface BLNewsFolder : BLNewsList
{
}

- (id)feedlyStreamIDWithUserID:(id)arg1;
- (id)localisedTitle;

// Remaining properties
@property(nonatomic) NSSet *feeds; // @dynamic feeds;

@end

