//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLNewsCacheNode.h"

@class NSDate, NSSet, NSString, NSURL;

@interface BLNewsItem : BLNewsCacheNode
{
}

+ (id)identifierForContentURL:(id)arg1;
+ (id)contentURLForIdentifier:(id)arg1;
@property(readonly, nonatomic) NSURL *linkURL;
@property(readonly, nonatomic) NSURL *contentURL;

// Remaining properties
@property(nonatomic) NSDate *crawledDate; // @dynamic crawledDate;
@property(nonatomic) _Bool linkCached; // @dynamic linkCached;
@property(nonatomic) _Bool linkCaching; // @dynamic linkCaching;
@property(retain, nonatomic) NSString *linkString; // @dynamic linkString;
@property(nonatomic) NSSet *lists; // @dynamic lists;
@property(nonatomic) _Bool saved; // @dynamic saved;
@property(nonatomic) _Bool savedDirty; // @dynamic savedDirty;
@property(nonatomic) int savedIndex; // @dynamic savedIndex;
@property(retain, nonatomic) NSString *sourceIdentifier; // @dynamic sourceIdentifier;
@property(nonatomic) NSString *sourceTitle; // @dynamic sourceTitle;
@property(nonatomic) NSString *summary; // @dynamic summary;
@property(nonatomic) NSString *title; // @dynamic title;
@property(nonatomic) _Bool unread; // @dynamic unread;
@property(nonatomic) _Bool unreadDirty; // @dynamic unreadDirty;

@end

