//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BLCacheDelegate.h"
#import "WKNavigationDelegate.h"

@class BLFeedly, BLNewsSignInViewController, NSDate, NSError, NSManagedObjectContext, NSMutableDictionary, NSNumber, NSString;

@interface BLNews : NSObject <BLCacheDelegate, WKNavigationDelegate>
{
    _Bool _syncing;
    int _nextSavedIndex;
    NSNumber *_cacheTotal;
    NSNumber *_cacheProgress;
    NSError *_cacheError;
    CDUnknownBlockType _syncErrorHandler;
    CDUnknownBlockType _backgroundFetchCompletionHandler;
    unsigned long long _backgroundTaskIdentifier;
    BLNewsSignInViewController *_signInViewController;
    BLFeedly *_feedly;
    CDUnknownBlockType _syncBlock;
    NSManagedObjectContext *_mainContext;
    NSManagedObjectContext *_backgroundContext;
    CDUnknownBlockType _cacheBlock;
    NSMutableDictionary *_cacheOperationsByIdentifier;
    NSMutableDictionary *_unreadByNotificationIdentifier;
}

+ (id)sharedInstance;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
@property(nonatomic) int nextSavedIndex; // @synthesize nextSavedIndex=_nextSavedIndex;
@property(retain, nonatomic) NSMutableDictionary *unreadByNotificationIdentifier; // @synthesize unreadByNotificationIdentifier=_unreadByNotificationIdentifier;
@property(retain, nonatomic) NSMutableDictionary *cacheOperationsByIdentifier; // @synthesize cacheOperationsByIdentifier=_cacheOperationsByIdentifier;
@property(copy, nonatomic) CDUnknownBlockType cacheBlock; // @synthesize cacheBlock=_cacheBlock;
@property(retain, nonatomic) NSManagedObjectContext *backgroundContext; // @synthesize backgroundContext=_backgroundContext;
@property(retain, nonatomic) NSManagedObjectContext *mainContext; // @synthesize mainContext=_mainContext;
@property(copy, nonatomic) CDUnknownBlockType syncBlock; // @synthesize syncBlock=_syncBlock;
@property(retain, nonatomic) BLFeedly *feedly; // @synthesize feedly=_feedly;
@property(retain, nonatomic) BLNewsSignInViewController *signInViewController; // @synthesize signInViewController=_signInViewController;
@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
@property(copy, nonatomic) CDUnknownBlockType backgroundFetchCompletionHandler; // @synthesize backgroundFetchCompletionHandler=_backgroundFetchCompletionHandler;
@property(copy, nonatomic) CDUnknownBlockType syncErrorHandler; // @synthesize syncErrorHandler=_syncErrorHandler;
@property(retain, nonatomic) NSError *cacheError; // @synthesize cacheError=_cacheError;
@property(retain, nonatomic) NSNumber *cacheProgress; // @synthesize cacheProgress=_cacheProgress;
@property(retain, nonatomic) NSNumber *cacheTotal; // @synthesize cacheTotal=_cacheTotal;
@property(nonatomic) _Bool syncing; // @synthesize syncing=_syncing;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *lastSyncDate;
@property(readonly, nonatomic) NSString *feedlyName;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationResponse:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)cacheOperationsDidFinish:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)registerBackgroundFetchCompletionHandler:(CDUnknownBlockType)arg1;
- (void)signOut;
- (void)resetCache;
- (id)cacheSize;
- (void)markItem:(id)arg1 asSaved:(_Bool)arg2;
- (void)markItem:(id)arg1 asRead:(_Bool)arg2;
- (void)markListAsRead:(id)arg1;
- (void)unsubscribeFeed:(id)arg1;
- (void)subscribeFeed:(id)arg1 folderIdentifiers:(id)arg2;
- (void)refreshCacheBlock;
- (void)endSync:(id)arg1 error:(id)arg2;
- (void)cancelSync;
- (void)startSync:(_Bool)arg1 metadataOnly:(_Bool)arg2;
- (void)startSync;
- (_Bool)autoSync;
- (id)fetchedLists;
- (id)fetchedItemWithIdentifier:(id)arg1;
- (id)fetchedListWithIdentifier:(id)arg1;
- (id)itemsFetchedResultsControllerWithList:(id)arg1 searchTerms:(id)arg2;
- (id)listsFetchedResultsController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

