//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "NSFetchedResultsControllerDelegate.h"
#import "UIDataSourceModelAssociation.h"
#import "UISplitViewControllerDelegate.h"

@class BLListViewController, BLStatusView, NSFetchedResultsController, NSSet, NSString;

@interface BLRootViewController : UITableViewController <NSFetchedResultsControllerDelegate, UIDataSourceModelAssociation, UISplitViewControllerDelegate>
{
    _Bool _collapsed;
    BLListViewController *_listViewController;
    BLStatusView *_statusView;
    NSFetchedResultsController *_listsFetchedResultsController;
    NSSet *_notificationIdentifiers;
}

@property(retain, nonatomic) NSSet *notificationIdentifiers; // @synthesize notificationIdentifiers=_notificationIdentifiers;
@property(retain, nonatomic) NSFetchedResultsController *listsFetchedResultsController; // @synthesize listsFetchedResultsController=_listsFetchedResultsController;
@property(nonatomic) _Bool collapsed; // @synthesize collapsed=_collapsed;
@property(retain, nonatomic) BLStatusView *statusView; // @synthesize statusView=_statusView;
@property(retain, nonatomic) BLListViewController *listViewController; // @synthesize listViewController=_listViewController;
- (void).cxx_destruct;
- (_Bool)splitViewController:(id)arg1 showDetailViewController:(id)arg2 sender:(id)arg3;
- (id)splitViewController:(id)arg1 separateSecondaryViewControllerFromPrimaryViewController:(id)arg2;
- (_Bool)splitViewController:(id)arg1 collapseSecondaryViewController:(id)arg2 ontoPrimaryViewController:(id)arg3;
- (void)splitViewController:(id)arg1 willChangeToDisplayMode:(long long)arg2;
- (long long)targetDisplayModeForActionInSplitViewController:(id)arg1;
- (void)controllerDidChangeContent:(id)arg1;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned long long)arg4 newIndexPath:(id)arg5;
- (void)controller:(id)arg1 didChangeSection:(id)arg2 atIndex:(unsigned long long)arg3 forChangeType:(unsigned long long)arg4;
- (void)controllerWillChangeContent:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)indexPathForElementWithModelIdentifier:(id)arg1 inView:(id)arg2;
- (id)modelIdentifierForElementAtIndexPath:(id)arg1 inView:(id)arg2;
- (void)registerListImpression:(id)arg1;
- (void)updateApplicationShortcutItems;
- (void)updateTableViewSelection:(_Bool)arg1;
- (void)configureCell:(id)arg1 withNewsList:(id)arg2;
- (void)refresh;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

