//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

@class NSArray, NSMutableArray, NSMutableDictionary;

@interface BLSettingsViewController : UITableViewController
{
    NSArray *_feedIdentifiers;
    NSArray *_feedTitles;
    NSMutableDictionary *_pendingSettingsByKey;
    NSMutableArray *_switchKeys;
}

@property(retain, nonatomic) NSMutableArray *switchKeys; // @synthesize switchKeys=_switchKeys;
@property(retain, nonatomic) NSMutableDictionary *pendingSettingsByKey; // @synthesize pendingSettingsByKey=_pendingSettingsByKey;
@property(retain, nonatomic) NSArray *feedTitles; // @synthesize feedTitles=_feedTitles;
@property(retain, nonatomic) NSArray *feedIdentifiers; // @synthesize feedIdentifiers=_feedIdentifiers;
- (void).cxx_destruct;
- (void)flushPendingSettings:(id)arg1;
- (void)doneAction:(id)arg1;
- (void)valueChangedAction:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (id)switchForKey:(id)arg1;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)awakeFromNib;

@end

