//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIImage;

@interface BLSearchTopicTableViewCell : UITableViewCell
{
    NSString *_topic;
    UIImage *_background;
}

@property(retain, nonatomic) UIImage *background; // @synthesize background=_background;
@property(retain, nonatomic) NSString *topic; // @synthesize topic=_topic;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

