//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BLSettingsViewController.h"

#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"

@class NSArray, NSString, SKPayment, SKProductsRequest;

@interface BLUpgradeSettingsViewController : BLSettingsViewController <SKProductsRequestDelegate, SKPaymentTransactionObserver>
{
    _Bool _restoring;
    _Bool _discount;
    NSString *_status;
    SKProductsRequest *_request;
    NSArray *_products;
    SKPayment *_payment;
}

@property(nonatomic) _Bool discount; // @synthesize discount=_discount;
@property(nonatomic) _Bool restoring; // @synthesize restoring=_restoring;
@property(retain, nonatomic) SKPayment *payment; // @synthesize payment=_payment;
@property(retain, nonatomic) NSArray *products; // @synthesize products=_products;
@property(retain, nonatomic) SKProductsRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueue:(id)arg1 removedTransactions:(id)arg2;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)restoreAction:(id)arg1;
- (void)purchaseAction:(id)arg1;
- (void)updateDiscount:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

