//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class BLNewsSignInViewController, UIActivityIndicatorView, UIButton, UILabel;

@interface BLWelcomeViewController : UIViewController
{
    BLNewsSignInViewController *_signInViewController;
    UIButton *_getStartedButton;
    UIActivityIndicatorView *_activityIndicator;
    UILabel *_errorLabel;
}

@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIButton *getStartedButton; // @synthesize getStartedButton=_getStartedButton;
@property(retain, nonatomic) BLNewsSignInViewController *signInViewController; // @synthesize signInViewController=_signInViewController;
- (void).cxx_destruct;
- (void)getStartedAction:(id)arg1;
- (void)presentError:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;

@end

