//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableURLRequest, NSObject<OS_dispatch_queue>;

@interface MBCloudTask : NSObject
{
    CDUnknownBlockType _redirectionHandler;
    CDUnknownBlockType _responseHandler;
    CDUnknownBlockType _fragmentDataHandler;
    CDUnknownBlockType _completeDataHandler;
    CDUnknownBlockType _completionHandler;
    NSMutableURLRequest *_request;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    id _mutableData;
}

+ (id)cloudTaskWithRequest:(id)arg1;
+ (id)cloudTaskWithURL:(id)arg1;
@property(retain, nonatomic) id mutableData; // @synthesize mutableData=_mutableData;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) NSMutableURLRequest *request; // @synthesize request=_request;
@property(copy) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(copy) CDUnknownBlockType completeDataHandler; // @synthesize completeDataHandler=_completeDataHandler;
@property(copy) CDUnknownBlockType fragmentDataHandler; // @synthesize fragmentDataHandler=_fragmentDataHandler;
@property(copy) CDUnknownBlockType responseHandler; // @synthesize responseHandler=_responseHandler;
@property(copy) CDUnknownBlockType redirectionHandler; // @synthesize redirectionHandler=_redirectionHandler;
- (void).cxx_destruct;
- (id)init;
- (id)initWithRequest:(id)arg1;

@end

