//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (BLCache)
- (id)convertToEncoding:(unsigned int)arg1 fromEncoding:(unsigned int)arg2;
- (unsigned int)textEncodingFromBOM;
- (id)parsedJSWithTextEncoding:(unsigned int)arg1;
- (id)parsedCSSWithTextEncoding:(unsigned int)arg1 baseURL:(id)arg2 cssURLs:(id *)arg3 otherURLs:(id *)arg4;
- (id)parsedHTMLWithTextEncoding:(unsigned int)arg1 baseURL:(id)arg2 cssURLs:(id *)arg3 otherURLs:(id *)arg4 addEnrichmentData:(id)arg5 parseEnrichmentData:(id *)arg6;
@end

